keys:
  - &colin_desktop age15kjwah37uddaqu5nphyk4vp0k7rrvmasqwaet9cr3ju7jh3zvpnq2s96le

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *colin_desktop
