/********* Sample code generated by the curl command line tool **********
 * All curl_easy_setopt() options are documented at:
 * https://curl.se/libcurl/c/curl_easy_setopt.html
 ************************************************************************/
#include <curl/curl.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <zip.h>

#define AACSDIR ".config/aacs"
#define OUTZIPFILE "keydb.zip"
#define OUTREGFILE "KEYDB.cfg"
#define STRBUF 256
#define FILEBUF 102400
#define URL "http://fvonline-db.bplaced.net/export/keydb_eng.zip"

#define STATUS_ERROR -1
#define STATUS_GOOD 0

int main(int argc, char *argv[]) {
  CURL *hnd;
  CURLcode ret;
  FILE *out_zip_fd, *out_reg_fd;
  char out_dir[STRBUF], out_zip_file[STRBUF], out_reg_file[STRBUF], buf[FILEBUF];
  int err;
  struct stat st = { 0 };
  zip_t *zip_file;
  zip_file_t *zip;
  zip_int64_t bytes_read;

  // 
  snprintf(out_dir, STRBUF , "%s/%s", getenv("HOME"), AACSDIR);
  snprintf(out_zip_file, STRBUF , "%s/%s", out_dir, OUTZIPFILE);
  snprintf(out_reg_file, STRBUF , "%s/%s", out_dir, OUTREGFILE);

  // Check if target dir exits, create it if not
  if (stat(out_dir, &st) == -1) {
    printf("AACS dir doesn't exist, creating...\n");
    if ((mkdir(out_dir, 0755)) != 0) {
      perror("mkdir");
      return STATUS_ERROR;
    }
  }

  // open and verify out_zip_file is writable
  if ((out_zip_fd = fopen(out_zip_file, "w")) == NULL) {
    perror("fopen");
    return STATUS_ERROR;
  }

  printf("Downloading AACS keys...\n");

  hnd = curl_easy_init();
  curl_easy_setopt(hnd, CURLOPT_BUFFERSIZE, 102400L);
  curl_easy_setopt(hnd, CURLOPT_URL, URL);
  curl_easy_setopt(hnd, CURLOPT_USERAGENT, "curl/8.12.1");
  curl_easy_setopt(hnd, CURLOPT_MAXREDIRS, 50L);
  curl_easy_setopt(hnd, CURLOPT_HTTP_VERSION, (long)CURL_HTTP_VERSION_2TLS);
  curl_easy_setopt(hnd, CURLOPT_FTP_SKIP_PASV_IP, 1L);
  curl_easy_setopt(hnd, CURLOPT_TCP_KEEPALIVE, 1L);
  curl_easy_setopt(hnd, CURLOPT_NOPROGRESS, 0L);
  curl_easy_setopt(hnd, CURLOPT_WRITEDATA, out_zip_fd);

  ret = curl_easy_perform(hnd);
  
  if (ret != CURLE_OK) {
    curl_easy_cleanup(hnd);
    fclose(out_zip_fd);
    return STATUS_ERROR;
  }

  curl_easy_cleanup(hnd);
  hnd = NULL;

  fclose(out_zip_fd);
  
  if ((zip_file = zip_open(out_zip_file, ZIP_RDONLY, &err)) == NULL) {
    perror("zip_open");
    return  STATUS_ERROR;
  }
  
  if((out_reg_fd = fopen(out_reg_file, "w+")) == NULL) {
    perror("fopen");
    zip_close(zip_file);
    return STATUS_ERROR;
  }


  if ((zip = zip_fopen(zip_file, OUTREGFILE, ZIP_FL_NOCASE)) == NULL) {
    perror("zip_fopen");
    fclose(out_reg_fd);
    zip_close(zip_file);
    return  STATUS_ERROR;
  }
  
  while((bytes_read = zip_fread(zip, buf, FILEBUF)) > 0) {
    fwrite(buf, 1, (size_t)bytes_read, out_reg_fd);
  }

  fclose(out_reg_fd);
  zip_fclose(zip);
  zip_close(zip_file);
  return (int)ret;
}
/**** End of sample code ****/
