#+TITLE: Colin's Emacs Configuration
#+AUTHOR: Colin Cockburn
#+DESCRIPTION: My Emacs configuration, inspired by DistroTube's configuration & Doom Emacs
#+STARTUP: showeverything
#+OPTIONS: toc:2

* Table Of Contents :toc:
- [[#important-packages][Important Packages]]
  - [[#straightel][Straight.el]]
  - [[#evil-mode][Evil Mode]]
  - [[#which-key][Which Key]]
  - [[#general-keybinds][General Keybinds]]
  - [[#nerd-icons][Nerd Icons]]
- [[#languagesmajor-modes][Languages/Major Modes]]
  - [[#json-mode][Json Mode]]
  - [[#markdown][Markdown]]
  - [[#nix-mode][Nix Mode]]
  - [[#elisp][ELisp]]
- [[#emacs-ui][Emacs UI]]
  - [[#dashboard][Dashboard]]
  - [[#extra-padding][Extra Padding]]
  - [[#general-ui-tweaks][General UI Tweaks]]
  - [[#mode-line][Mode Line]]
  - [[#themeing][Themeing]]
- [[#editor-config][Editor Config]]
  - [[#disable-autosaving][Disable autosaving]]
  - [[#indentation][Indentation]]
  - [[#golden-ratio][Golden Ratio]]
  - [[#sudo-edit][Sudo Edit]]
  - [[#zooming-inout][Zooming In/Out]]
- [[#org-mode-config][Org-Mode Config]]
  - [[#indentation-1][Indentation]]
  - [[#table-of-contents][Table of Contents]]
  - [[#modern-org][Modern Org]]
  - [[#tempo-config][Tempo config]]
- [[#utilities][Utilities]]
  - [[#magit][Magit]]
  - [[#popper][Popper]]
  - [[#treemacs][Treemacs]]
  - [[#vterm][Vterm]]
  - [[#vertico][Vertico]]

* Important Packages
Please note that the order in this section is important, Ex if Straight isn't first some packages might not get installed.
** Straight.el
Straight is my preffered package manager, it is configured to add :straight t by default.
#+begin_src emacs-lisp
  ;; Install Straight
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name
          "straight/repos/straight.el/bootstrap.el"
          (or (bound-and-true-p straight-base-dir)
              user-emacs-directory)))
        (bootstrap-version 7))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  ;; Install use-package
  (straight-use-package 'use-package)

  ;; Set straight by default
  (setq straight-use-package-by-default t)
#+end_src

** Evil Mode
#+begin_src emacs-lisp
  (use-package evil
    :init
    (setq evil-want-keybinding nil)
      :config
          (evil-mode 1)
          (use-package evil-collection
            :config
            (evil-collection-init)))
#+end_src

** Which Key
#+begin_src emacs-lisp
  (use-package which-key
    :init
      (which-key-mode 1)
    :config
    (setq which-key-side-window-location 'bottom
            which-key-sort-order #'which-key-key-order-alpha
            which-key-sort-uppercase-first nil
            which-key-add-column-padding 1
            which-key-max-display-columns nil
            which-key-min-display-lines 6
            which-key-side-window-slot -10
            which-key-side-window-max-height 0.25
            which-key-idle-delay 0.8
            which-key-max-description-length 25
            which-key-allow-imprecise-window-fit t
            which-key-separator " → " ))
#+end_src
** General Keybinds
#+begin_src emacs-lisp
  (use-package general
    :config
    (general-evil-setup)
    ;; set up 'SPC' as the global leader key
    (general-create-definer leader-keys
      :states '(normal insert visual emacs)
      :keymaps 'override
      :prefix "SPC" ;; set leader
      :global-prefix "M-SPC") ;; access leader in insert mode

    (leader-keys
      "."       '(find-file :wk "Find file")
      "f c"     '((lambda () (interactive) (find-file "~/.config/emacs/config.org")) :wk "Edit emacs config")
      "TAB TAB" '(comment-line :wk "Comment lines"))

    ;; General keybinds
    (leader-keys
      "b"   '(:ignore t :wk "Buffer")
      "b b" '(switch-to-buffer :wk "Switch buffer")
      "b i" '(ibuffer :wk "Ibuffer")
      "b k" '(kill-this-buffer :wk "Kill this buffer")
      "b n" '(next-buffer :wk "Next buffer")
      "b p" '(previous-buffer :wk "Previous buffer")
      "b r" '(revert-buffer :wk "Reload buffer"))

    (leader-keys
      "e"   '(:ignore t :wk "Evaluate")    
      "e b" '(eval-buffer :wk "Evaluate elisp in buffer")
      "e d" '(eval-defun :wk "Evaluate defun containing or after point")
      "e e" '(eval-expression :wk "Evaluate and elisp expression")
      "e l" '(eval-last-sexp :wk "Evaluate elisp expression before point")
      "e r" '(eval-region :wk "Evaluate elisp in region")) 

     (leader-keys
      "h"     '(:ignore t :wk "Help")
      "h f"   '(describe-function :wk "Describe function")
      "h v"   '(describe-variable :wk "Describe variable"))

     (leader-keys
      "t" '(:ignore t :wk "Toggle")
      "t l" '(display-line-numbers-mode :wk "Toggle line numbers")
      "t t" '(visual-line-mode :wk "Toggle truncated lines"))

     (leader-keys
       "o" '(:ignore t :wk "Org-Mode")
       "o e" '(org-edit-special :wk "Edit source block")
       "o E" '(org-edit-src-exit :wk "Exit source block"))
  )

#+end_src
** Nerd Icons
#+begin_src emacs-lisp
  (use-package nerd-icons)
#+end_src
* Languages/Major Modes
** Json Mode
#+begin_src emacs-lisp
  (use-package json-mode
    :mode "\\.json\\'")
#+end_src

** Markdown
As much as I would like to use Org for everything, unfortunately that's not feasible.
#+begin_src emacs-lisp
  (use-package markdown-mode
    :mode "\\.md\\'")
#+end_src
** Nix Mode
#+begin_src emacs-lisp
  (use-package nix-mode
    :mode "\\.nix\\'"
    :config
    (use-package nixfmt
      :config
      (add-hook 'nix-mode-hook 'nixfmt-on-save-mode)))
#+end_src
** ELisp
Add in a formater for ELisp
#+begin_src emacs-lisp
  (use-package elisp-autofmt
    :config
    (add-hook 'elisp-mode-hook 'elisp-autofmt-mode))
#+end_src
* Emacs UI
** Dashboard
#+begin_src emacs-lisp
  (use-package dashboard
    :init
    (setq initial-buffer-choice (lambda () (get-buffer-create dashboard-buffer-name)))
    (setq dashboard-center-content t)
    (setq dashboard-vertically-center-content t)
    :config
    (dashboard-setup-startup-hook)
    (setq dashboard-startup-banner "~/.config/emacs/osaka.png")
    (setq dashboard-item-shortcuts '((recents   . "r")
                                     (bookmarks . "b")
                                     (projects  . "p")
                                     (agenda    . "a")
                                     (registers . "e")))
    (setq dashboard-display-icons-p t)
    (setq dashboard-icon-type 'nerd-icons))
#+end_src
** Extra Padding
#+begin_src emacs-lisp
  (use-package spacious-padding
    :config
    (setq spacious-padding-widths '(:internal-border-width 5))
    (spacious-padding-mode 1))
#+end_src

** General UI Tweaks
#+begin_src emacs-lisp
  ;; UI settings
  (setq inhibit-startup-message t)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  ;; enable line numbers in programming modes only
  (add-hook 'prog-mode-hook #'display-line-numbers-mode)
#+end_src

** Mode Line
#+begin_src emacs-lisp
  (use-package doom-modeline
    :init (doom-modeline-mode 1)
    :config
    (setq doom-modeline-buffer-file-name-style 'truncate-nil))
#+end_src
** Themeing
I use stylix with Nix for all my theming needs, it applies colourschemes automatically so no configuration in Emacs is needed.

* Editor Config
** Disable autosaving
Auto saving creates a bunch of random files that get hard to work with in VCS projects, and I never use them anyways.
#+begin_src emacs-lisp
  (auto-save-mode nil)
#+end_src

** Indentation
#+begin_src emacs-lisp
  (setq tab-width 4)

  ;; Enables visual indentation markers, options for format are fill, column, character and bitmap
  (use-package highlight-indent-guides
   :init
   (setq highlight-indent-guides-method 'bitmap)
   :config
     (add-hook 'prog-mode-hook 'highlight-indent-guides-mode))
#+end_src

** Golden Ratio
Automatically resizes windows when editing them
#+begin_src emacs-lisp
  (use-package golden-ratio
    :config
    (setq golden-ratio-auto-scale t)
    (golden-ratio-mode 1))
#+end_src

** Sudo Edit
[[https://github.com/nflath/sudo-edit][sudo-edit]] gives us the ability to open files with sudo privileges or switch over to editing with sudo privileges if we initially opened the file without such privileges.

#+begin_src emacs-lisp
  (use-package sudo-edit
    :config
      (leader-keys
        "f u" '(sudo-edit-find-file :wk "Sudo find file")
        "f U" '(sudo-edit :wk "Sudo edit file")))
#+end_src

** Zooming In/Out
You can use the bindings CTRL plus =/- for zooming in/out.  You can also use CTRL plus the mouse wheel for zooming in/out.

#+begin_src emacs-lisp
  (global-set-key (kbd "C-=") 'text-scale-increase)
  (global-set-key (kbd "C--") 'text-scale-decrease)
  (global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
  (global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
#+end_src

* Org-Mode Config
** Indentation
This should make formatting in Org-mode a bit better
#+begin_src emacs-lisp
  (setq org-src-tab-acts-natively t)
#+end_src

** Table of Contents
#+begin_src emacs-lisp
  (use-package toc-org
      :commands toc-org-enable
      :init (add-hook 'org-mode-hook 'toc-org-enable))
#+end_src

** Modern Org
#+begin_src emacs-lisp
  (use-package org-modern
    :config
    (add-hook 'org-mode-hook #'org-modern-mode)
    (add-hook 'org-agenda-finalize-hook #'org-modern-agenda))
#+end_src

** Tempo config
Org-tempo is not a separate package but a module within org that can be enabled.  Org-tempo allows for '<s' followed by TAB to expand to a begin_src tag.  Other expansions available include:

| Typing the below + TAB | Expands to ...                           |
|------------------------+------------------------------------------|
| <a                     | '#+BEGIN_EXPORT ascii' … '#+END_EXPORT  |
| <c                     | '#+BEGIN_CENTER' … '#+END_CENTER'       |
| <C                     | '#+BEGIN_COMMENT' … '#+END_COMMENT'     |
| <e                     | '#+BEGIN_EXAMPLE' … '#+END_EXAMPLE'     |
| <E                     | '#+BEGIN_EXPORT' … '#+END_EXPORT'       |
| <h                     | '#+BEGIN_EXPORT html' … '#+END_EXPORT'  |
| <l                     | '#+BEGIN_EXPORT latex' … '#+END_EXPORT' |
| <q                     | '#+BEGIN_QUOTE' … '#+END_QUOTE'         |
| <s                     | '#+BEGIN_SRC' … '#+END_SRC'             |
| <v                     | '#+BEGIN_VERSE' … '#+END_VERSE'         |

#+begin_src emacs-lisp
  (require 'org-tempo)
#+end_src

* Utilities
** Magit
Magit is a git interface for emacs.
#+begin_src emacs-lisp
  (use-package magit
    :config
    (leader-keys
      "g"  '(magit :wk "Launch Magit")))
#+end_src

** Popper
Lets you declare buffers as popup windows and allows you to toggle them with a keybind
#+begin_src emacs-lisp
  (use-package popper
    :config
    (setq popper-reference-buffers
        '("\\*Messages\\*"
          "Output\\*$"
          "^\\*vterm.*\\*$"  vterm-mode 
          help-mode
          compilation-mode))
    (popper-mode +1)
    (popper-echo-mode +1)
    (leader-keys
      "p"   '(:ignore t :wk "Popper")
      "p t" '(popper-toggle :wk "Toggle Popper Buffer")
      "p c" '(popper-cycle  :wk "Cycle Popper Buffer")
    )
  )
#+end_src

** Treemacs
Treemacs is a file explorer for emacs
#+begin_src emacs-lisp
  (use-package treemacs
    :config
    (leader-keys "t T" '(treemacs :wk "Toggle Treemacs"))
    (use-package treemacs-evil
      :after (treemacs evil))
    (use-package treemacs-nerd-icons)
    (use-package treemacs-magit)
  )
#+end_src

** Vterm
Vterm provides a terminal to use in emacs, requires cmake & libterm to build.  A lot of Linux distros provide a package for this as well so you don't have to complile it yourself if you don't want to.
#+begin_src emacs-lisp
  (use-package vterm
    :config
    (setq vterm-kill-buffer-on-exit t
          vterm-always-compile-module t)
    (leader-keys "v" '(vterm :wk "Launch VTerm"))
  )
#+end_src

** Vertico
Improves upon the default completion interface in Emacs by providing a performant and minimalistic completion UI.
#+begin_src emacs-lisp
  (use-package vertico
    :init
    (vertico-mode))
#+end_src
